name: Terraform Plan

on:
  pull_request:
    branches:
      - main
    paths:
      - "modules/**"
      - "envs/**"
      - ".github/workflows/terraform-plan.yml"

  push:
    branches:
      - terraform-cicd
    paths:
      - "modules/**"
      - "envs/**"
      - ".github/workflows/terraform-plan.yml"

permissions:
  contents: read

jobs:
  terraform-plan-dev:
    name: Terraform Plan Dev
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: envs/dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform fmt check
        run: terraform fmt -check -recursive ../..

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform validate
        run: terraform validate

      - name: Create runtime tfvars
        run: |
          cat > runtime.tfvars <<EOF
          allowed_ssh_cidr = "${{ secrets.TF_VAR_ALLOWED_SSH_CIDR }}"
          ssh_public_key_content = "${{ secrets.SSH_PUBLIC_KEY_CONTENT }}"
          EOF

      - name: Terraform plan
        run: terraform plan -input=false -var-file=ci.tfvars
